### ISSUE TITLE
rlwpx.free.fr entries aren't extracted back to hosts.block.d/...hosts.hosts files

### ISSUE THREAD

**Issue by bjauy** [gaenserich/hostsblock#10]
Tested with pre-alpha, it looks like the directories are created, the file is extracted from 7z, and later there's no information about redirections. Below are parts of log created with verbosity=4:

    rlwpx.free.fr.WPFF.hrsk.7z is a 7z archive. Will use 7za to extract it...
    Extracting entries from /var/cache/hostsblock/rlwpx.free.fr.WPFF.hrsk.7z...
    Created directory /dev/shm/hostsblock/rlwpx.free.fr.WPFF.hrsk.7z.d.
    Moved rlwpx.free.fr.WPFF.hrsk.7z to /dev/shm/hostsblock/rlwpx.free.fr.WPFF.hrsk.7z.d.
    [...]
    Un7zipped rlwpx.free.fr.WPFF.hrsk.7z.
    Extracting obvious entries from rlwpx.free.fr.WPFF.hrsk.7z...
    Extracted obvious entries from rlwpx.free.fr.WPFF.hrsk.7z.
    Extracting less-obvious entries from rlwpx.free.fr.WPFF.hrsk.7z
    Extracted less-obvious entries from rlwpx.free.fr.WPFF.hrsk.7z.
    Deleting /dev/shm/hostsblock/rlwpx.free.fr.WPFF.hrsk.7z.d...

**Comment by gaenserich** [comment]
Fixed in git commit a84a4f326b61d9acda8569eca8c602f693ead554 (grep misidentified the extracted files from rlwpx.free.fr as binaries and skipped them)!
