### ISSUE TITLE
Add openrc init.d script

### ISSUE THREAD

**Issue by somenxavier** [gaenserich/hostsblock#101]
Please, as you put systemd init scrit, please do the same with openrc

**Comment by gaenserich** [comment]
I am unfortunately not acquainted with openrc, and have no machine with it
installed to test on. I will accept contributions, if you wish to provide
the appropriate scripts/configs.

**Comment by somenxavier** [comment]
I do not know so. I'm just a user.
You can ask here https://lists.artixlinux.org/listinfo Here there are good developers.

**Comment by gaenserich** [comment]
If this is a feature you want, you yourself should ask your distro
maintainers and package maintainers to create the necessary files, which
they can either share with me or use in their own packaging. OpenRC is
fairly rare, and it's far from standard practice for developers to provide
openrc scripts or configs; rather, that sort of thing seems to be where the
work of a package maintainer begins.
