### ISSUE TITLE
[SOLVED] How to temporary disable the whole block list, for checking?

### ISSUE THREAD

**Issue by lliseil** [gaenserich/hostsblock#11]
Hello,
Please how to temporary disable the whole block list?
I suspect my hostsblock config may causes my inability to download any data from Google Webmaster Tools. On my main computer with hostblocks it occurs with four different browsers (plus firefox no plugin). Clicking the "Download this table" on GWT gives _no_ result but the following error in Firefox console:

    AssertionError: Assertion failed: GA not loaded yet.

There's no visible URL on GWT's button so I cannot make use of `hostsblock-url-check` in this case.
It works on my laptop therefore the need to check my main computer's network conf.

**Comment by gaenserich** [comment]
If you are using hostsblock with a DNS caching daemon, just shut down the
daemon. Otherwise, just replace the /etc/hosts file, if that is the target
file, e.g. mv /etc/hosts /etc/hosts.old; mv /etc/hostsblock/hosts.head
/etc/hosts (if you have a hosts.head)
Am 26.01.2015 11:11 schrieb "Cyrille" <notifications@github.com>:

**Comment by Sadi58** [comment]
For such "one-off" cases I use this zenity-script:

```
#!/bin/bash

sudo_password="$( gksudo --print-pass --message 'Provide permission to make system changes: Type your password or press Cancel.' -- : 2>/dev/null )"

if [[ ${?} != 0 || -z ${sudo_password} ]]
then
    exit 4
fi
if ! sudo -kSp '' [ 1 ] <<<"${sudo_password}" 2>/dev/null
then
    exit 4
fi

sudo -Sp '' mv /etc/hosts.block /etc/hosts.block.1 <<<"${sudo_password}"
sudo -Sp '' /etc/init.d/dnsmasq restart <<<"${sudo_password}"
```
There's another to re-enable the hostsblock afterwards.
But if this is a website likely to be visited again, I add the proper address to the whitelist and restart the hostsblock.

**Comment by lliseil** [comment]
/me running hostsblock along with dnsmasq. Sadi58's scripts run fine (after replacing `init` with `systemctl`)
I can download the GWT tables while hostsblock is temporary disabled :)
Thank you v much gaesenrich and Sadi58 for your help!

Also I cannot get which url is blocked on GWT while hostsblock's running, causing the aforementioned issue and 'Google Analytic not loaded yet' error message. `www.google-analytics.com` and `ssl.gstatic.com` are the two only urls displayed in FF's console when effectively downloading GWT's data and:
hostsblock-urlcheck www.google-analytics.com

    Verifying that the given page is blocked or unblocked
    NOT BLOCKED: 'www.google-analytics.com' Block? [y/N] 
    Page domain verified. Scan the whole page for other domains for (un)blocking? [y/N] y
    NOT BLOCKED: 'www.google.com' Block? [y/N] 
    Whole-page scan completed.
hostsblock-urlcheck ssl.gstatic.com

    Verifying that the given page is blocked or unblocked
    NOT BLOCKED: 'ssl.gstatic.com' Block? [y/N] 
    Page domain verified. Scan the whole page for other domains for (un)blocking? [y/N] y
    Whole-page scan completed.
