### ISSUE TITLE
man pages for hostsblock, hostsblock-urlcheck, hostsblock.conf

### ISSUE THREAD

**Issue by gaenserich** [gaenserich/hostsblock#19]
Provide detailed man pages (hostsblock-urlcheck.8  hostsblock.8  hostsblock.conf.8).

**Comment by pickfire** [comment]
Leave this to me.

**Comment by gaenserich** [comment]
awesome!

**Comment by pickfire** [comment]
No problem, I am currently working on [fisherman](//fisherman.sh)'s documentation, I will work on this after that.

**Comment by Wabuo** [comment]
Hey ho
I'm looking in to it right now maybe I will write them ...

**Comment by pickfire** [comment]
It's in troff, I had gotten interested in it some time ago but if you wrote it, I can help to fix the styling.

**Comment by Wabuo** [comment]
I will tray it with the ronn project so I can use markdown to write them ...

**Comment by pickfire** [comment]
Nice
