### ISSUE TITLE
Add license info [was: Add alternatives]

### ISSUE THREAD

**Issue by pickfire** [gaenserich/hostsblock#22]
There is an alternative [hosts](https://github.com/StevenBlack/hosts) blocking software which is written in python, *well documentated* README.md and only changes */etc/hosts*. It uses the **KISS principle** which you can just `python updateHostsFile.py` to use it. I hope you can add it to the [README.md](https://github.com/gaenserich/hostsblock). I also hope that you can add a license to hostsblock (I recommend [wftpl](http://www.wtfpl.net/).

**Comment by gaenserich** [comment]
Thank you for the information. In my own capacity as a AUR packager of this script, I have stated this to be under the GPL, so I'll carry that over to this.

**Comment by pickfire** [comment]
I think that it should be better to show LICENSE or COPYING that it is GPL. And what about putting the alternative in README.md?

**Comment by pickfire** [comment]
I have tried the other hosts blocking method, works nice. I don't have much knowledge about what this project is doing, I hope that it can be simpler.

Want me to help maintaining it?

**Comment by gaenserich** [comment]
That would be immensely helpful. I don't really have the time to actively
maintain it any more.

Jacob A. van der Kolk <http://personal.psu.edu/jav209>
Lecturer in German
Ph.D. Candidate in German Literature and Culture, ABD
Department of Germanic and Slavic Languages and Literatures
The Pennsylvania State University
jav209@psu.edu
PGP Public Key <http://www.personal.psu.edu/jav209/jvdk.gpg> (plaintext
<http://www.personal.psu.edu/jav209/jvdk.asc>)

2016-02-13 5:08 GMT-05:00 Ivan Tham <notifications@github.com>:

**Comment by pickfire** [comment]
@gaenserich You can make me a collaborator (or probably add more prople), I will do my best. If there is any questions, I can ask you.

**Comment by gaenserich** [comment]
I added you and Sadi!

**Comment by pickfire** [comment]
@gaenserich Thanks a lot.

**Comment by Sadi58** [comment]
@gaenserich Thank you for your trust although I have more ideas than skills to contribute ; -)

**Comment by pickfire** [comment]
@Sadi58 I have both idea and skills (haven't sharpened yet), but I don't have a lot of time.
