### ISSUE TITLE
dnscacher handling

### ISSUE THREAD

**Issue by mkoskar** [gaenserich/hostsblock#26]
I believe that `hostsblock.conf` should mention `dnscacher` variable and its recognized values. In my case `dnsmasq` auto-configuration fails (due to non-standard `dnsmasq` config) so I set `dnscacher=manual` which works well up to the point of `hostsblock` trying to restart it resulting in:

    [WARN] FAILED to restart manual.

That could be fixed by enhancing below test condition:

    # IF WE HAVE A DNS CACHER, LET'S RESTART IT
    if [ "$dnscacher" != "none" ]; then
        _notify 3 "Restarting $dnscacher..."

**Comment by gaenserich** [comment]
I think I might strip out the automatic detection of the dnscacher and just provide a configuration option to allow restarting it. That would make this much simpler.

**Comment by pickfire** [comment]
@gaenserich Yeah, I think the automatic detection of the dnscacher might be damaging, I hope that the README.md mention more about how it uses dnscacher too.

@mkoskar I agree about that, I am using `dnsmasq` to cache tor dns requests, I doesn't know much about dnscacher currently, need some research.

**Comment by gaenserich** [comment]
Indeed, a robust wiki is probably more beneficial than additional code.

**Comment by gaenserich** [comment]
Oh, and this was resolved a while back, though I got rid of the last vestige here: 4301a83
