### ISSUE TITLE
Add option to disable configuration checks.

### ISSUE THREAD

**Issue by enodata** [gaenserich/hostsblock#28]
Configuration that hostsblock script checks for is not the only possible, f.i. I usually avoid modifying dnsmasq.conf directly and place config overrides in /etc/dnsmasq.d/hostsblock instead. Also, "prepend domain-name-servers 127.0.0.1" is not always required.

It would be helpful to have a way to disable hostsblock config checks and assume that everything is already configured and working properly.

**Comment by gaenserich** [comment]
I agree. My next task is to strip out the checks and work on the documentation.

**Comment by gaenserich** [comment]
Oops. Fixed this a while back, but didn't post it as such. Cf. 4301a83
