### ISSUE TITLE
302 Redirected URLs Don't Work

### ISSUE THREAD

**Issue by SpotComms** [gaenserich/hostsblock#30]
Sites that use a 302 redirect on a URL cause cURL to break, its fixed by adding "-L" or "--location" to the cURL arguments. However hostsblock will still fail to parse the resulting file if its compressed, because it'll save it as the initial URL and not as the redirected URL, which doesn't end with a file extension resulting in it being treated as a plaintext file. I'd submit a pull request to fix it, but I'm not skilled enough in BASH to do so.

**Comment by gaenserich** [comment]
For which URL are you observing this behavior?

**Comment by gaenserich** [comment]
File extension issue fixed in abf8a30b28099ae781b252eb7f55f37d026149f4.
