### ISSUE TITLE
gzip: invalid option -- 'z' when running command 'hostsblock' and 'hostsblock-urlchecker'

### ISSUE THREAD

**Issue by maniqui** [gaenserich/hostsblock#34]
Hi.
It seems that everywhere the `gzip` command is used, there is a `-z` parameter passed along, which makes it fail. 
The consequences are that the hostsblock.db.gz isn't created properly and then, other commands fail too.

The fix is pretty straightforward: remove the `-z` parameter.
BTW, the `-z` parameter is also used with the command `pigz` (parallel gzip), but as I don't use that program, I'm not sure if this issue affects it too. I'd guess it does.

**Comment by gaenserich** [comment]
fixed! 5762f2bd7f6597db47a1d6f3e998694058217c34

**Comment by maniqui** [comment]
There are still some places in [hostsblock-common.sh](https://github.com/gaenserich/hostsblock/blob/6f0f04a34526313b581028c7f1ecb6c13554c3da/src/hostsblock-common.sh) where the incorrect  `-z` (for gzip) is being used:

Lines: 
[#L228](https://github.com/gaenserich/hostsblock/blob/6f0f04a34526313b581028c7f1ecb6c13554c3da/src/hostsblock-common.sh#L228)
[#L289](https://github.com/gaenserich/hostsblock/blob/6f0f04a34526313b581028c7f1ecb6c13554c3da/src/hostsblock-common.sh#L289)
[#L313](https://github.com/gaenserich/hostsblock/blob/6f0f04a34526313b581028c7f1ecb6c13554c3da/src/hostsblock-common.sh#L313)

**Comment by Sadi58** [comment]
@maniqui : I can't see any remaining "-z" option, are you sure you haven't confused it with "-dc" which seems valid?
