### ISSUE TITLE
You have an extra space after the @ symbol on line 261 of hostsblock-common.sh.

### ISSUE THREAD

**Issue by hpeters** [gaenserich/hostsblock#35]
Line# 261 is:
echo " $@ " >> "$whitelist"

It should be:
echo " $@" >> "$whitelist"

I should add that this makes manully added whitelist urls via hostsblock-urlcheck.sh not work after the hosts.block file is updated.

**Comment by gaenserich** [comment]
Fixed in 622941b677f8612ab9d9732abb7176edb9ef2ba3
