### ISSUE TITLE
Mispelled variable that breaks whitelisting when updating.

### ISSUE THREAD

**Issue by eduardoeae** [gaenserich/hostsblock#36]
In hostsblock.sh and hostsblock-common.sh there is a variable misspelled 4 times.
"whilelist" Should be "whitelist" (L -> T). This causes white-listing not applying when updating hosts.

**Comment by mkoskar** [comment]
I generally as far as `bash` best practices goes always set `set -eu` depending on error handling code even `-E` might be of interest. `-u` should catch errors like above (btw. I didn't check the source to confirm it).

**Comment by gaenserich** [comment]
@mkoskar thanks for the tip!
fixed: 6f0f04a34526313b581028c7f1ecb6c13554c3da
