### ISSUE TITLE
notify when completed?

### ISSUE THREAD

**Issue by Sadi58** [gaenserich/hostsblock#4]
I don't know about other distros or MacOS but adding the following line at the very end displays a nice notification each time when this cron job is completed under Ubuntu:

DISPLAY=:0.0 XAUTHORITY=~/.Xauthority notify-send "Hostsblock updated just now!"

**Comment by gaenserich** [comment]
in /etc/hostsblock/hostsblock.conf just put in
"postprocess() {
     DISPLAY=:0.0 XAUTHORITY=~/.Xauthority notify-send "Hostsblock updated just now!"
}"
You may need to run this with sudo -u [main X user here] preappended.

**Comment by Sadi58** [comment]
Thanks.
Using the command `sudo -u sadi hostsblock` resulted in fatal error with permission problems for me.
However, I could get the notification by using `/home/sadi/.Xauthority` instead of `~/.Xauthority` in the configuration file.

**Comment by gaenserich** [comment]
Sorry, I mean that you should add this to hostsblock.conf:
```
postprocess() {
    sudo -u sadi DISPLAY=:0.0 XAUTHORITY=~/.Xauthority notify-send "Hostsblock updated just now!"
}
```

**Comment by Sadi58** [comment]
Perhaps something like this might give us something that can be incorporated into the default configuration file in the future, although this is beyond my elementary scripting skills:
```
postprocess() {
USER="$(users | awk -F ' ' '{print $2}')"
sudo -u "$USER" DISPLAY=:0.0 XAUTHORITY=~/.Xauthority notify-send "Hostsblock updated just now!"
}
```

**Comment by Sadi58** [comment]
This didn't work for me, but this works:
```
postprocess() {
USER="$(users | awk -F ' ' '{print $2}')"
DISPLAY=:0.0 XAUTHORITY=/home/"$USER"/.Xauthority notify-send "Hostsblock updated just now!"
}
```

**Comment by gaenserich** [comment]
We can certainly include the example in documentation, but I'm less
inclined to make this default, especially since many if not most probably
wouldn't be interested as to whether or not one particular
cronjob/background service finishes successfully.
Am 25.04.2015 05:41 schrieb "Sadi Yumuşak" <notifications@github.com>:

**Comment by pickfire** [comment]
@Sadi58 I think you could add it to the wiki for this, someone may be interested.

**Comment by Sadi58** [comment]
@pickfire There's no wiki page for this project yet, but maybe one day ;-)
Perhaps README.md file and https://gaenserich.github.io/hostsblock/ might be used as a starting point.

BTW, at the end I have put together the following piece of code, and added it to my `hostsblock-launcher` at https://github.com/Sadi58/hostsblock for this purpose of **notifying users**:

```
# create message
changes=$(grep -c "CHANGES FOUND" "/tmp/hostsblock.log")
if [ "$changes" -gt 0 ]
then
	echo "Hostsblock has just checked and updated $changes blocklist(s)" > "/tmp/hostsblock-launcher-message.txt"
# notify user(s)
	xuser=$(who | grep " \:[0-9]" | awk '{print $1}')
	xdisplay=$(who | grep " \:[0-9]" | awk '{print $5}' | sed "s/[(|)]//g")
	message=$(cat "/tmp/hostsblock-launcher-message.txt")
	echo "$xuser" > "/tmp/xusers.txt"
	echo "$xdisplay" > "/tmp/xdisplays.txt"
	while read -r -u3 xuser; read -r -u4 xdisplay
	do
		DISPLAY="$xdisplay" XAUTHORITY="/home/"$xuser"/.Xauthority" su "$xuser" -c "notify-send '$message' -i gtk-dialog-info" &
	done 3<"/tmp/xusers.txt" 4<"/tmp/xdisplays.txt"
else
	echo "Hostsblock has just checked and found no updates" > "/tmp/hostsblock-launcher-message.txt"
# notify user(s)
	xuser=$(who | grep " \:[0-9]" | awk '{print $1}')
	xdisplay=$(who | grep " \:[0-9]" | awk '{print $5}' | sed "s/[(|)]//g")
	message=$(cat "/tmp/hostsblock-launcher-message.txt")
	echo "$xuser" > "/tmp/xusers.txt"
	echo "$xdisplay" > "/tmp/xdisplays.txt"
	while read -r -u3 xuser; read -r -u4 xdisplay
	do
		DISPLAY="$xdisplay" XAUTHORITY="/home/"$xuser"/.Xauthority" su "$xuser" -c "notify-send '$message' -i gtk-dialog-info" &
	done 3<"/tmp/xusers.txt" 4<"/tmp/xdisplays.txt"
fi
```
