### ISSUE TITLE
invalid gzip option

### ISSUE THREAD

**Issue by davidbecker** [gaenserich/hostsblock#42]
I installed hostsblock from AUR, the mentioned _/etc/hostsblock/rc.conf_ file wasn't created (it appears to be that the hostsblock.conf file is the file that holds the configuration now, so the documentation is probably out of date)
````bash
$ ls /etc/hostsblock 
black.list  hosts.head  hostsblock.conf  white.list
````
so I just ran
````bash
$ sudo /usr/bin/hostsblock
gzip: invalid option -- 'z'
Try `gzip --help' for more information.
````
on a subsequent run there was no message, and I got my shell back after a few seconds

edit: when I clear the cache directory in _/var/cache/hostsblock/_ I get the message back

**Comment by ilpianista** [comment]
Duplicate of #34

**Comment by Sadi58** [comment]
@davidbecker : it seems the AUR package is outdated as this issue has been resolved here in git version.

**Comment by davidbecker** [comment]
@Sadi58 you are right about that, I just looked at the *.tar.gz in AUR and the script is indeed different to the current git version.
