### ISSUE TITLE
database format and _check_url

### ISSUE THREAD

**Issue by Lompik** [gaenserich/hostsblock#43]
I am just trying to understand the format for the file `/var/lib/hostsblock.db`.
It seems to me it is something like `"%IP %address ! %source"`
However 

   - line 262 in common: ` _strip_entries " $@$" "$annotate"` . The extra `$` in the first argument makes it match the address and the end of line. I would expect "$@ !"
   - Is there a special format for local files ? the "!" character is escape in many calls to sed and grep. So the database ends up with `"%IP %address \! %source"`

**Comment by gaenserich** [comment]
#1 Thanks for catching that error. It is fixed in d4ebbf4.
#2 I assigned the "!" as a special marker arbitrarily. It's intended to be there, but I'm perfectly fine changing that if it becomes a hinderance.

**Comment by Lompik** [comment]
Is the maker "!" or "\!" ?? The fix c2389ae91fc0ceeb42ebe107d9727f5a81c6b613 won't cut it for the first case. (There is no need to escape "!" in calls to grep and sed). Right now my database uses *two* delimiter: "!" and "\!".  Can this be due to a version mistmatch ? I have the version `0.999.2-1` installed.
