### ISSUE TITLE
[Conf file] question on default configuration

### ISSUE THREAD

**Issue by lliseil** [gaenserich/hostsblock#44]
Hi, in hostsblock.conf all DEFAULT settings are set for a NO DNS CACHER setup. But that one:

    hostsfile="/etc/hosts.block"  # For use with a dnscacher, e.g dnsmasq

Of course unless I'm wrong. Please enlight me.

**Comment by Sadi58** [comment]
Lines 17 & 18 here in github:
```
#hostsfile="/etc/hosts.block" # For use with a dnscacher, e.g dnsmasq
hostsfile="/etc/hosts" # DEFAULT. If not using a dns caching daemon
```

**Comment by lliseil** [comment]
Oops, my mistake I meant the

    HEAD FILE
    hostshead="0" # DEFAULT
    #hostshead="/etc/hostsblock/hosts.head" # If not using dns caching.

**Comment by Sadi58** [comment]
It seems you're right. I've never noticed this as I use DNS caching.

**Comment by lliseil** [comment]
Made me scratch my hair a bit. Alright then.

**Comment by lliseil** [comment]
I confirm that hostsblock-0.999.3-1 still has a geek, hard to read rc file and... that it runs fine on the boxes I have it *kiss*ing my Web surf :)
