### ISSUE TITLE
hostsblock-0.999.2-1: same version, 2 different scripts and results

### ISSUE THREAD

**Issue by lliseil** [gaenserich/hostsblock#45]
hostsblock-0.999.2-1 is installed on two of my machines running Arch; are up-to-date, AUR included (as of yesterday). 
hostsblock (and dnsmask) conf files are identical on both machines. It works on box One does but not on the other.

box One
With DNS caching on, hosts.block is updated and so on, single issue:

    oct. 29 00:03:35 One hostsblock[3169]: gzip: invalid option -- 'z'
    oct. 29 00:03:35 One hostsblock[3169]: Try `gzip --help' for more information.
    oct. 29 00:03:38 One hostsblock[3169]: sort: write failed: standard output: Broken pipe
    oct. 29 00:03:38 One hostsblock[3169]: sort: write error
from line 210 in /usr/bin/hostsblock --which is absent from the same version script on box Zero ~8-|

Box Zero
With DNS caching ON, hostsblock exit and hosts.block file is not updated

    oct. 29 00:00:01 Zero hostsblock[13141]: [FATAL] NO VIABLE DNSCACHER CONFIGURATION FOUND. EXITING...
    oct. 29 00:00:01 Zero systemd[1]: hostsblock.service: Main process exited, code=exited, status=1/FAILURE
    oct. 29 00:00:01 Zero systemd[1]: Failed to start Block bad domains system-wide.
    oct. 29 00:00:01 Zero systemd[1]: hostsblock.service: Unit entered failed state.
    oct. 29 00:00:01 Zero systemd[1]: hostsblock.service: Failed with result 'exit-code'.
I tripled checked if dnsmasq.conf are identical between the two boxes and they are.

But I noted `/usr/bin/hostsblock` differ consequently. pacman -Qi says both are v0.999.2-1, with a different size ?#-|

For the moment I changed hostsblock on box One to run without DNS caching, and it runs. Though it still checks dnsmask:
 /usr/bin/hostsblock

    [INFO] Auto-detecting dnscaching settings...
    [INFO] DNSMASQ does NOT have the correct 'listen-address' entry.
    [INFO] DNSMASQ incorrectly configured.
    [INFO] Checking blocklists for updates...

I suspect a script change forgetting to update version. What's your suggestion?

**Comment by lliseil** [comment]
I confirm that hostsblock-0.999.3-1 still has a geek, hard to read rc file and... that it runs fine on the boxes I have it kissing my Web surf :) No more script diffs or issues since October 30th.

**Comment by gaenserich** [comment]
I'm not sure whether to interpret this as a generally happy response or
otherwise...

Jacob A. van der Kolk <http://personal.psu.edu/jav209>
Lecturer in German
Ph.D. Candidate in German Literature and Culture, ABD
Department of Germanic and Slavic Languages and Literatures
The Pennsylvania State University
jav209@psu.edu
PGP Public Key <http://www.personal.psu.edu/jav209/jvdk.gpg> (plaintext
<http://www.personal.psu.edu/jav209/jvdk.asc>)

2015-11-02 19:34 GMT-05:00 Kozaki <notifications@github.com>:

**Comment by lliseil** [comment]
Look it twice, "*runs fine*" and the *happy smiley* should clear your doubt. Not even counting "*No more script diffs or issues*"
