### ISSUE TITLE
False "CHANGES FOUND": someonewhocares.org 

### ISSUE THREAD

**Issue by Sadi58** [gaenserich/hostsblock#49]
I've noticed that the blocklist at http://someonewhocares.org/hosts/hosts gets updated too frequently, and when I checked I didn't see such frequent updates there. For instance, hostsblock somehow has recently found changes every day although the file itself has this line: "Last updated: Nov 19th, 2015 at 21:40"
I wonder if this is caused by a server flaw or what.

**Comment by pickfire** [comment]
@Sadi58 It is true, it really did get updated, look at the rss feed, I contribute sites needed to block for them.

**Comment by gaenserich** [comment]
For future reference: Hostsblock uses the -z flag on curl, which asks the
server for the modtime on the requested file and compares it to the mtime
on the local cached file. From the curl man file:
```
-z, --time-cond <date expression>|<file>
              (HTTP/FTP) Request a file that has been modified later than
the given time and date, or one  that  has  been  modified
              before  that time. The <date expression> can be all sorts of
date strings or if it doesn't match any internal ones, it
              is taken as a filename and tries to get the modification date
(mtime) from <file> instead. See the curl_getdate(3) man
              pages for date expression details.

              Start  the  date  expression with a dash (-) to make it
request for a document that is older than the given date/time,
              default is a document that is newer than the specified
date/time.

              If this option is used several times, the last one will be
used.
```
In the past, hostsblock has glicked out like this when there was a bug in
curl that broke this flag.

**Comment by pickfire** [comment]
Ah, this is actually how `hostsblock` currently check for changes, I thought it is using `diff`.

Thanks a lot for for the reference.
