### ISSUE TITLE
Add adaway source list

### ISSUE THREAD

**Issue by pickfire** [gaenserich/hostsblock#51]
I saw this adaway source file at https://github.com/StevenBlack/hosts/blob/master/data/adaway.org/update.info, I hope that it can be a default as I found the adaway sources list nice.

**Comment by Sadi58** [comment]
I've added it the adaway blocklist at http://adaway.org/hosts.tx to my .conf file as well as the following ;-)
https://raw.githubusercontent.com/Sadi58/hostsblock/master/indicator/hosts.txt
But I wonder why this file at **github** always appears "updated" although I haven't even viewed it :\)

**Comment by pickfire** [comment]
> But I wonder why this file at github always appears "updated" although I haven't even viewed it :)

What do you mean?

**Comment by Sadi58** [comment]
I have this list of undesirable domains which I'd like to share and use as part of the hostsblock lists in the .conf file, and I thought it could be a good idea to maintain it at github.
But every time hostsblock checks it if has been updated, it is detected as "updated" (although no change has been made in the list) probably resulting in an unnecessary process of downloading and including the same list again.

**Comment by pickfire** [comment]
@Sadi58 Probably it didn't do a diff.

**Comment by Sadi58** [comment]
Strange; why shouldn't do a diff consistently for this list and not any others? I wonder if it has something to do with the extremely long URL and the resulting file names in the cache, which hostsblock apparently had to abbreviate like this: "https:..raw.githubusercontent.com.Sadi58.hostsblock.master.indicator.hosts.txt"

**Comment by pickfire** [comment]
@Sadi58 It seems like it is weird, I think I need to use a separate issue for this after I had confirmed it.

**Comment by Sadi58** [comment]
@pickfire OK, thanks.
