### ISSUE TITLE
missing rc.conf

### ISSUE THREAD

**Issue by paoloap** [gaenserich/hostsblock#56]
I wanted to install this package, but I didn't find it on AUR. So I decided to adopt the "general installation" from this git: I downloaded the tarball and extracted it, but I found out that the rc.conf link pointed to nowhere... now I see that it has been deleted from the git 5 days ago.
What happened? :(

**Comment by Sadi58** [comment]
I deleted it as I thought it was no longer needed, being replaced with hostsblock.conf (same file only with a new change actually).
It seems we should also make one or two more changes, like the line `install -Dm644 rc.conf /etc/hostsblock/rc.conf`
What do you mean when you say `rc.conf link` - any other change required?

**Comment by paoloap** [comment]
Thanks very much!
Right now I'm preparing an examination, I will test asap integration with Vimb web browser

**Comment by pickfire** [comment]
@paoloap, how's it?
