### ISSUE TITLE
Can you update the link to aur?

### ISSUE THREAD

**Issue by somenxavier** [gaenserich/hostsblock#57]
In the page it's not updated

**Comment by pickfire** [comment]
@somenxavier Is there anything wrong with the link to aur?

**Comment by somenxavier** [comment]
Yes: this is the correct: https://aur.archlinux.org/packages/hostsblock
but this appears on website https://aur.archlinux.org/packages.php?ID=58976
![captura_2016-07-28_20-16-17](https://cloud.githubusercontent.com/assets/89915/17224181/318a51c4-5500-11e6-92ed-86a750fb96b6.png)

**Comment by pickfire** [comment]
@somenxavier Which website? The result I get is from `cower -i hostsblock`.

**Comment by somenxavier** [comment]
@pickfire See [previous picture](https://cloud.githubusercontent.com/assets/89915/17224181/318a51c4-5500-11e6-92ed-86a750fb96b6.png)

**Comment by pickfire** [comment]
@somenxavier Oh, that broken aur page. Thanks a lot for pointing it out, I hope that you can send in a pull request for correcting that in the gh-pages branch so that you can take the credit. :)

**Comment by somenxavier** [comment]
I can't. I have no tech skills but I consider a bit exhagerated: a pull request just for changing a link? Really?

**Comment by pickfire** [comment]
@somenxavier, thanks a lot for filling this issue.

This is updated in `add0234`.

**Comment by somenxavier** [comment]
Thanks
