### ISSUE TITLE
How to install it correct together with dnsmasq?

### ISSUE THREAD

**Issue by Wabuo** [gaenserich/hostsblock#58]
I'm missing a section about how to use it together with dnsmasq. And how to configure dnsmasq correct

Bay the way I think a link to a tutorial about how to make Chrome/Chromium use the system dns/hostfile would also be appreciated.

**Comment by Sadi58** [comment]
1) Re: dnsmasq you might find useful info here: https://gaenserich.github.io/hostsblock

2) The hosts block script performs a **system-wide** blocking of domains listed in `/etc/hosts.block` (or `/etc/hosts` as you might prefer) so you don't need to make anything else in any web browser settings.

**Comment by Wabuo** [comment]
@Sadi58 In case of Chrome/Chromium you need to disable the intern DNS stuff. I think this [superuser.com](https://superuser.com/questions/723703/why-is-chromium-bypassing-etc-hosts-and-dnsmasq) answer answers it quite god.

And thx for the link

**Comment by Sadi58** [comment]
Thanks a lot!
I agree that **a DNS config section in README.md** file would be helpful indeed.
I think I didn't know this internal DNS setting in Chrome but I have it disabled (default setting maybe?).
It's called "_Use a prediction service to load pages more quickly_" in version 50.x now.
So `chrome://dns/` tells me  "_DNS pre-resolution and TCP pre-connection is disabled._"
