### ISSUE TITLE
Broken/Usless Manpages

### ISSUE THREAD

**Issue by Wabuo** [gaenserich/hostsblock#59]
The Manpages are currently nearly empty and really useless!

**Comment by pickfire** [comment]
@Wabuo Yes, I agree about that. If you could send in a patch, I would just accept it.

By the way, I am now less active in this project. If you want to be a collaborator, feel free.

**Comment by pickfire** [comment]
I would appreciate your great help to solve #19.

**Comment by Wabuo** [comment]
Sorry my bad I haven't seen the other one.
Close because double!
