### ISSUE TITLE
configuration file name

### ISSUE THREAD

**Issue by Sadi58** [gaenserich/hostsblock#6]
While testing the new pre-alpha version, got this error: "Configuration file /etc/hostsblock/hostsblock.conf NOT FOUND, using defaults."
It seems the file "rc.conf" should be renamed as "hostsblock.conf"

**Comment by Sadi58** [comment]
I wonder if the file `rc.conf` should still remain here though :\)

**Comment by gaenserich** [comment]
Should remain in the repository or should remain in use instead of
hostsblock.conf?
Am 24.04.2015 10:05 schrieb "Sadi Yumuşak" <notifications@github.com>:

**Comment by Sadi58** [comment]
I thought `rc.conf`should no longer remain in the repository as it has been replaced with `hostsblock.conf` if I don't miss something.

**Comment by gaenserich** [comment]
A maintainer more familiar with git would have relocated the old rc.conf to
a legacy branch. :-/
Am 25.04.2015 03:52 schrieb "Sadi Yumuşak" <notifications@github.com>:

**Comment by pickfire** [comment]
There isn't a *legacy* branch, just *master* and another branch. To add a legacy branch just `git branch legacy XXXXXX` where XXXXXX is the **abbrev-commit** of the old commit. Then, `git checkout legacy` to work on the *legacy* to work on it.
