### ISSUE TITLE
Issues with hostsblock-urlcheck

### ISSUE THREAD

**Issue by botain** [gaenserich/hostsblock#71]
Hi gaenserich, beautiful work.

There seems to be a couple of problems using hostsblock-urlcheck or hostsblock -c. For me, every URL I test is reported as UNBLOCKED and hostsblock offers to block it for me. If I choose 'yes' and the URL was already blocked, a duplicate line will be added to black.list and running hostsblock-urlcheck again will still report the URL as unblocked.

I uncovered three issues here:

1. The file hostsblock.db.gz does not get updated properly with entries from the blacklist. See line 467.
2. The function _check_url creates an "escaped" version of the test URL and uses that to grep hostsblock.db.gz. This always fails, because the ``-F`` option tells grep that the search string is literal, i.e. not a RE. I'm not sure of your intent - you could remove the ``-F`` and then the escaped strings would match, or you could just not escape the periods in the search strings and don't use ``-F`` either.
3. If the symlink was invoked, the variable _URL is not set as it would have been using hostsblock -c.

Here is my patch - can you please take a look?

```
80d79                                                      
<     _url_escaped=$(echo "$@" | sed "s/\./\\\./g")        
82c81                                                      
<         _matches=$(pigz -dc "$annotate" | grep -F " $_url_escaped ")                                                 
---                                                        
>         _matches=$(pigz -dc "$annotate" | grep -F " $@ ")                                                            
84c83                                                      
<         _matches=$(gzip -dc "$annotate" | grep -F " $_url_escaped ")                                                 
---                                                        
>         _matches=$(gzip -dc "$annotate" | grep -F " $@ ")                                                            
281a281,282                                                
>     # If run from symlink "hostsblock-urlcheck" _URL will not be set by getopts                                      
>     [ "$_URL" == "" ] && _URL="$1"                       
467c468                                                    
<             echo "$redirecturl $_blacklistline \! $blacklist" >> "$tmpdir"/"${annotate##*/}".tmp                     
---                                                        
>             echo "$redirecturl $_blacklistline \! $blacklist" >> "$tmpdir"/hostsblock/"${annotate##*/}".tmp
```

**Comment by gaenserich** [comment]
Looks good! I used "-F" because it causes significant performance improvements. This is a big enough find to issue a new release.

**Comment by gaenserich** [comment]
e4bbb043feaf4204fd6f898ff533ac6c8a805e58
