### ISSUE TITLE
Add anti-cryptomining list

### ISSUE THREAD

**Issue by glitsj16** [gaenserich/hostsblock#77]
With all the buzz about cryptomining in web browsers it might be nice to add a list like [nocoin](https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt) to the blocklists section in hostsblock.conf:
```
# anti-cryptomining in browser (github.com/hoshsadiq/adblock-nocoin-list)
'https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt'
```
Regards.

**Comment by gaenserich** [comment]
Thanks! A great addition to the list. See efee8ca4a08867a076c5ac8a0a93d7a149214239.
