### ISSUE TITLE
Add the CoinBlockerLists

### ISSUE THREAD

**Issue by ZeroDot1** [gaenserich/hostsblock#78]
Hi, I'm the creator of the CoinBlockerLists, is it possible to add the CoinBlockerLists to your project?
https://github.com/ZeroDot1/CoinBlockerLists
CoinBlockerLists Short URL: [https://git.io/vFFKT](https://git.io/vFFKT)

| Format | Description | URL |
| --- | --- | --- |
| List | This list contains all domains - A list for administrators to prevent mining in networks| [RAW = list.txt](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list.txt) |
| List | This list contains all optional domains - An additional list for administrators| [RAW = list_optional.txt](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_optional.txt) |
| List | This list contains all browser mining domains - A list to prevent browser mining only| [RAW = list_browser.txt](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt) |
| Hosts | This list contains all domains - A hostslist for administrators to prevent mining in networks| [RAW = hosts](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts) |
| Hosts | This list contains all optional domains - An additional hostslist for administrators| [RAW = hosts_optional](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts_optional) |
| Hosts | This list contains all browser mining domains - A hostslist to prevent browser mining only| [RAW = hosts_browser](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts_browser) |
| List | This list contains all IPs - A additional list for administrators to prevent mining in networks| [RAW = MiningServerIPList.txt](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/MiningServerIPList.txt) |

**Comment by gaenserich** [comment]
Thanks for the lists! Added via 2dc51cdc97db0d73bcb00d68b54da0f8e929ee36

**Comment by ZeroDot1** [comment]
Thank you very much :)
