### ISSUE TITLE
install.sh broken

### ISSUE THREAD

**Issue by ohnonot** [gaenserich/hostsblock#87]
I've been using hostsblock on archlinux, installed via aur, no major problems.  
today i tried to install it on ubuntu, "the easy way".  

basically everything failed.

1. it seems the group hostsblock already existed on my computer, and the installation failed.
so i exited the script and created user & group hostsblock manually, then re-ran install.sh.
however, `$HOMEDIR` is defined [only if user hostsblock does __not__ exist yet](https://github.com/gaenserich/hostsblock/blob/a7e8a453ea87a8ed2ec37d829ed24e1b4c8fecb2/install.sh#L26)! the script later happily (and silently) installed config files into the root directory /.

2. even worse, `$DESTDIR` is not checked for being an existing directory, only [making sure it's not zero length, but that twice](https://github.com/gaenserich/hostsblock/blob/a7e8a453ea87a8ed2ec37d829ed24e1b4c8fecb2/install.sh#L22). why not use `[ -d "$d" ] && [ -w "$d" ]` here???
i must have accidenatlly input some garbage, because the script then happily (and silently) installed executables into the root directory `/`.

frankly, considering that hostsblock itself is a bash script, i am appalled.

**Comment by gaenserich** [comment]
Thanks for letting me know. Give the latest git version a try.

Should be resolved by f0738805676d3ded67e730e9b0b22d45387fb6dd

**Comment by ohnonot** [comment]
i am re-opening this, please see [this post](http://forums.debian.net/viewtopic.php?f=16&t=129202#p679513):
> I installed this program, and it renamed my home directory to 'hostsblock'. Anyhow, long story short, I ended up losing a bunch of files whilst uninstalling and getting things back to normal—config files and scripts that took hours and hours to make.

i am not yet 100% sure that the install.sh script caused it, but it's a fair guess.
