### ISSUE TITLE
Always pdate /etc/hosts.block when white/black.list changed

### ISSUE THREAD

**Issue by mnick** [gaenserich/hostsblock#9]
Right now, `/etc/hosts.block` does will not always be updated when the while/black.list files are changed. This is because `$changed` is only set to true when the downloaded files change, but not when these configuration files change. The `$changed` part should therefore also monitor these files.

**Comment by gaenserich** [comment]
Added an option to force an update from the command line invocation of hostsblock, e.g. hostsblock -u 
e126072
