### ISSUE TITLE
Invalid paths in systemd unit files for Debian/Ubuntu distributions

### ISSUE THREAD

**Issue by glitsj16** [gaenserich/hostsblock#90]
Hi, after enjoying the newly improved 0.999.8 on Arch Linux, I wanted to get that working on some Ubuntu machines too. During configuration I noticed the hardcoded paths in 2 of the systemd unit files are invalid on these distributions (and friends):
- [hostsblock-dnsmasq-restart.service](https://github.com/gaenserich/hostsblock/blob/master/systemd/hostsblock-dnsmasq-restart.service) uses `/usr/bin/systemctl` in ExecStart, but this should be `/bin/systemctl` instead.
- [hostsblock-hosts-clobber.service](https://github.com/gaenserich/hostsblock/blob/master/systemd/hostsblock-hosts-clobber.service) uses `/usr/bin/bash` in ExecStart, but this should be `/bin/bash` instead.

Newer systemd releases dropped the need for using full paths in unit files. But I guess that's not going to be the easy solution, as these non-rolling distributions typically carry older systemd versions. Not entirely sure how this could be fixed. Perhaps a note to point this out during installation via [install.sh](https://github.com/gaenserich/hostsblock/blob/master/install.sh) would be welcome until a proper fix can be merged?

Regards

**Comment by gaenserich** [comment]
Oh. Good point. I'm fixing that right now. `install.sh` will now insert the
appropriate paths in.

**Comment by gaenserich** [comment]
Fixed in v0.999.8.1
