### ISSUE TITLE
Blacklisted entries are alternatively removed or added every other update

### ISSUE THREAD

**Issue by bjauy** [gaenserich/hostsblock#93]
I've noticed that after update to 0.999.8 hostsblock started to randomly bypass some of the entries added to blacklist.

It looks like these lines:
https://github.com/gaenserich/hostsblock/blob/e47ec630a905fdf0730f86a3c4d183296cad3168/src/hostsblock.sh#L680-L681

add only entries from `black.list` which weren't included in previous version. 

Shouldn't `grep` search in `.new` file instead?

**Comment by gaenserich** [comment]
Indeed it should read `.new`. Fixed in d14ec998ae22aa9c7b495f52cf26adeed25c8d4a
