### ISSUE TITLE
hostsblock.sh: Line 795: hostsblock.conf: No rights

### ISSUE THREAD

**Issue by IAoVI** [gaenserich/hostsblock#97]
Probably fucked up somewhere but can't figure it out.

1. I installed the package from AUR
2. As superuser copied the files from hostsblock/config.examples/ to hostsblock/
3. As superuser edited hostsblock.conf
4. ran "$ sudo systemctl enable --now hostsblock.timer"

`systemctl status hostsblock
● hostsblock.service - Block bad domains system-wide
   Loaded: loaded (/usr/lib/systemd/system/hostsblock.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2019-09-06 20:32:28 CEST; 36min ago
  Process: 536 ExecStart=/usr/lib/hostsblock.sh (code=exited, status=1/FAILURE)
 Main PID: 536 (code=exited, status=1/FAILURE)

Sep 06 20:32:28 daniel-laptop systemd[1]: Starting Block bad domains system-wide...
Sep 06 20:32:28 daniel-laptop hostsblock.sh[536]: /usr/lib/hostsblock.sh: Zeile 795: /var/lib/hostsblock/hostsblock.conf: Keine Berechtigung
Sep 06 20:32:28 daniel-laptop systemd[1]: hostsblock.service: Main process exited, code=exited, status=1/FAILURE
Sep 06 20:32:28 daniel-laptop systemd[1]: hostsblock.service: Failed with result 'exit-code'.
Sep 06 20:32:28 daniel-laptop systemd[1]: Failed to start Block bad domains system-wide.`

**Comment by gaenserich** [comment]
chown -R hostsblock: hostsblock /var/lib/hostsblock

IAoVI <notifications@github.com> schrieb am Fr., 6. Sep. 2019, 15:20:

**Comment by IAoVI** [comment]
$ sudo hostsblock -u
Dearchiver for zip NOT FOUND. Optional functions which use this format will be skipped.
Checking blocklists and/or redirectlists for updates...
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
    FAILED to refresh/download blocklist https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts
    FAILED to refresh/download blocklist https://v.firebog.net/hosts/AdguardDNS.txt
    FAILED to refresh/download blocklist https://adaway.org/hosts.txt
    FAILED to refresh/download blocklist https://v.firebog.net/hosts/static/w3kbl.txt
    FAILED to refresh/download blocklist https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Spam/hosts
    FAILED to refresh/download blocklist https://raw.githubusercontent.com/StevenBlack/hosts/master/data/KADhosts/hosts
    FAILED to refresh/download blocklist https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
    FAILED to refresh/download blocklist http://pgl.yoyo.org/as/serverlist.php?hostformat=hosts&mimetype=plaintext
    FAILED to refresh/download blocklist https://raw.githubusercontent.com/StevenBlack/hosts/master/data/UncheckyAds/hosts
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
    FAILED to refresh/download blocklist https://v.firebog.net/hosts/Easylist.txt
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
    FAILED to refresh/download blocklist https://hosts-file.net/grm.txt
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
    FAILED to refresh/download blocklist https://v.firebog.net/hosts/Easyprivacy.txt
    FAILED to refresh/download blocklist https://v.firebog.net/hosts/Prigent-Ads.txt
    FAILED to refresh/download blocklist https://www.squidblacklist.org/downloads/dg-ads.acl
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
    FAILED to refresh/download blocklist https://hosts-file.net/hphosts-partial.txt
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
    FAILED to refresh/download blocklist https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
Failed to get filetime: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw    FAILED to refresh/download blocklist https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.2o7Net/hosts
: Keine Berechtigung
    FAILED to refresh/download blocklist https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
    FAILED to refresh/download blocklist https://hosts-file.net/ad_servers.txt
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
    FAILED to refresh/download blocklist https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
    FAILED to refresh/download blocklist https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
    FAILED to refresh/download blocklist https://hosts-file.net/exp.txt
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
    FAILED to refresh/download blocklist https://mirror1.malwaredomains.com/files/justdomains
    FAILED to refresh/download blocklist https://v.firebog.net/hosts/Prigent-Malware.txt
    FAILED to refresh/download blocklist https://hosts-file.net/emd.txt
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
    FAILED to refresh/download blocklist https://hosts-file.net/psh.txt
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
    FAILED to refresh/download blocklist https://v.firebog.net/hosts/Prigent-Phishing.txt
Failed to get filetime: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
    FAILED to refresh/download blocklist https://www.malwaredomainlist.com/hostslist/hosts.txt
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
    FAILED to refresh/download blocklist https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
    FAILED to refresh/download blocklist https://phishing.army/download/phishing_army_blocklist_extended.txt
Failed to get filetime: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
    FAILED to refresh/download blocklist https://ransomwaretracker.abuse.ch/downloads/LY_C2_DOMBL.txt
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
    FAILED to refresh/download blocklist https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt
    FAILED to refresh/download blocklist https://ransomwaretracker.abuse.ch/downloads/CW_C2_DOMBL.txt
Failed to get filetime: Keine Berechtigung
    FAILED to refresh/download blocklist https://mirror.cedia.org.ec/malwaredomains/immortal_domains.txt
    FAILED to refresh/download blocklist https://ransomwaretracker.abuse.ch/downloads/TC_C2_DOMBL.txt
    FAILED to refresh/download blocklist https://ransomwaretracker.abuse.ch/downloads/TL_C2_DOMBL.txt
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
    FAILED to refresh/download blocklist https://v.firebog.net/hosts/Shalla-mal.txt
Failed to get filetime: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
Failed to get filetime: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
    FAILED to refresh/download blocklist https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
    FAILED to refresh/download blocklist https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
    FAILED to refresh/download blocklist https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Risk/hosts
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
    FAILED to refresh/download blocklist https://www.squidblacklist.org/downloads/dg-malicious.acl
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
    FAILED to refresh/download blocklist https://zerodot1.gitlab.io/CoinBlockerLists/hosts
find: Failed to restore initial working directory: /home/danielw: Keine Berechtigung
Changes found among blocklists and/or redirectlists. Extracting to /var/lib/hostsblock/hosts.block.new...
  Extracting blocklists...
grep: /var/lib/hostsblock/cache/hosts-file.net.grm.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/hosts-file.net.grm.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/hosts-file.net.hphosts-partial.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/hosts-file.net.hphosts-partial.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/reddestdream.github.io.Projects.MinimalHosts.etc.MinimalHostsBlocker.minimalhosts: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/reddestdream.github.io.Projects.MinimalHosts.etc.MinimalHostsBlocker.minimalhosts: Keine Berechtigung
grep: /var/lib/hostsblock/cache/raw.githubusercontent.com.StevenBlack.hosts.master.data.KADhosts.hosts: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/raw.githubusercontent.com.StevenBlack.hosts.master.data.KADhosts.hosts: Keine Berechtigung
grep: /var/lib/hostsblock/cache/raw.githubusercontent.com.StevenBlack.hosts.master.data.add.Spam.hosts: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/raw.githubusercontent.com.StevenBlack.hosts.master.data.add.Spam.hosts: Keine Berechtigung
grep: /var/lib/hostsblock/cache/v.firebog.net.hosts.static.w3kbl.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/v.firebog.net.hosts.static.w3kbl.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/adaway.org.hosts.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/adaway.org.hosts.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/v.firebog.net.hosts.AdguardDNS.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/v.firebog.net.hosts.AdguardDNS.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/raw.githubusercontent.com.anudeepND.blacklist.master.adservers.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/raw.githubusercontent.com.anudeepND.blacklist.master.adservers.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/s3.amazonaws.com.lists.disconnect.me.simple_ad.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/s3.amazonaws.com.lists.disconnect.me.simple_ad.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/hosts-file.net.ad_servers.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/hosts-file.net.ad_servers.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/v.firebog.net.hosts.Easylist.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/v.firebog.net.hosts.Easylist.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/pgl.yoyo.org.as.serverlist.php.hostformat.hosts.mimetype.plaintext: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/pgl.yoyo.org.as.serverlist.php.hostformat.hosts.mimetype.plaintext: Keine Berechtigung
grep: /var/lib/hostsblock/cache/raw.githubusercontent.com.StevenBlack.hosts.master.data.UncheckyAds.hosts: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/raw.githubusercontent.com.StevenBlack.hosts.master.data.UncheckyAds.hosts: Keine Berechtigung
grep: /var/lib/hostsblock/cache/www.squidblacklist.org.downloads.dg-ads.acl: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/www.squidblacklist.org.downloads.dg-ads.acl: Keine Berechtigung
grep: /var/lib/hostsblock/cache/v.firebog.net.hosts.Easyprivacy.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/v.firebog.net.hosts.Easyprivacy.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/v.firebog.net.hosts.Prigent-Ads.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/v.firebog.net.hosts.Prigent-Ads.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/gitlab.com.quidsup.notrack-blocklists.raw.master.notrack-blocklist.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/gitlab.com.quidsup.notrack-blocklists.raw.master.notrack-blocklist.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/raw.githubusercontent.com.StevenBlack.hosts.master.data.add.2o7Net.hosts: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/raw.githubusercontent.com.StevenBlack.hosts.master.data.add.2o7Net.hosts: Keine Berechtigung
grep: /var/lib/hostsblock/cache/raw.githubusercontent.com.crazy-max.WindowsSpyBlocker.master.data.hosts.spy.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/raw.githubusercontent.com.crazy-max.WindowsSpyBlocker.master.data.hosts.spy.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/s3.amazonaws.com.lists.disconnect.me.simple_malvertising.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/s3.amazonaws.com.lists.disconnect.me.simple_malvertising.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/mirror1.malwaredomains.com.files.justdomains: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/mirror1.malwaredomains.com.files.justdomains: Keine Berechtigung
grep: /var/lib/hostsblock/cache/hosts-file.net.exp.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/hosts-file.net.exp.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/hosts-file.net.emd.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/hosts-file.net.emd.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/hosts-file.net.psh.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/hosts-file.net.psh.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/mirror.cedia.org.ec.malwaredomains.immortal_domains.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/mirror.cedia.org.ec.malwaredomains.immortal_domains.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/www.malwaredomainlist.com.hostslist.hosts.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/www.malwaredomainlist.com.hostslist.hosts.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/bitbucket.org.ethanr.dns-blacklists.raw.8575c9f96e5b4a1308f2f12394abd86d0927a4a0.bad_lists.Mandiant_APT1_Report_Appendix_D.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/bitbucket.org.ethanr.dns-blacklists.raw.8575c9f96e5b4a1308f2f12394abd86d0927a4a0.bad_lists.Mandiant_APT1_Report_Appendix_D.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/v.firebog.net.hosts.Prigent-Malware.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/v.firebog.net.hosts.Prigent-Malware.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/v.firebog.net.hosts.Prigent-Phishing.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/v.firebog.net.hosts.Prigent-Phishing.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/phishing.army.download.phishing_army_blocklist_extended.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/phishing.army.download.phishing_army_blocklist_extended.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/gitlab.com.quidsup.notrack-blocklists.raw.master.notrack-malware.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/gitlab.com.quidsup.notrack-blocklists.raw.master.notrack-malware.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/ransomwaretracker.abuse.ch.downloads.RW_DOMBL.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/ransomwaretracker.abuse.ch.downloads.RW_DOMBL.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/ransomwaretracker.abuse.ch.downloads.CW_C2_DOMBL.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/ransomwaretracker.abuse.ch.downloads.CW_C2_DOMBL.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/ransomwaretracker.abuse.ch.downloads.LY_C2_DOMBL.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/ransomwaretracker.abuse.ch.downloads.LY_C2_DOMBL.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/ransomwaretracker.abuse.ch.downloads.TC_C2_DOMBL.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/ransomwaretracker.abuse.ch.downloads.TC_C2_DOMBL.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/ransomwaretracker.abuse.ch.downloads.TL_C2_DOMBL.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/ransomwaretracker.abuse.ch.downloads.TL_C2_DOMBL.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/zeustracker.abuse.ch.blocklist.php.download.domainblocklist: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/zeustracker.abuse.ch.blocklist.php.download.domainblocklist: Keine Berechtigung
grep: /var/lib/hostsblock/cache/v.firebog.net.hosts.Shalla-mal.txt: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/v.firebog.net.hosts.Shalla-mal.txt: Keine Berechtigung
grep: /var/lib/hostsblock/cache/raw.githubusercontent.com.StevenBlack.hosts.master.data.add.Risk.hosts: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/raw.githubusercontent.com.StevenBlack.hosts.master.data.add.Risk.hosts: Keine Berechtigung
grep: /var/lib/hostsblock/cache/www.squidblacklist.org.downloads.dg-malicious.acl: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/www.squidblacklist.org.downloads.dg-malicious.acl: Keine Berechtigung
grep: /var/lib/hostsblock/cache/zerodot1.gitlab.io.CoinBlockerLists.hosts: Keine Berechtigung
/usr/lib/hostsblock.sh: Zeile 60: /var/lib/hostsblock/cache/zerodot1.gitlab.io.CoinBlockerLists.hosts: Keine Berechtigung
FAILED TO COMPILE BLOCK/REDIRECT ENTRIES FROM URLS IN /var/lib/hostsblock/block.urls INTO /var/lib/hostsblock/hosts.block. EXITING...

**Comment by gaenserich** [comment]
hostsblock -u -v

Kein sudo.


IAoVI <notifications@github.com> schrieb am Fr., 6. Sep. 2019, 16:05:

**Comment by IAoVI** [comment]
[hostsblock-u-v.zip](https://github.com/gaenserich/hostsblock/files/3585854/hostsblock-u-v.zip)

**Comment by gaenserich** [comment]
Try chmod -R u+rw /var/lib/hostsblock

**Comment by IAoVI** [comment]
Did that with no real change. Then deleted the cache folder, created it again and ran chown -v hostsblock cache  (again). Looks better. I guess this is the expected output (minus the urls that can't be reached, but that's something different)

[hostsblockuv.txt](https://github.com/gaenserich/hostsblock/files/3586621/hostsblockuv.txt)

Thanks a lot
